<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <ThreadPoolDir>$(SolutionDir)..\src\modules\thread_pool</ThreadPoolDir>
  </PropertyGroup>
  <ItemGroup>
    <BuildMacro Include="ThreadPoolDir">
      <Value>$(ThreadPoolDir)</Value>
    </BuildMacro>
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="$(ThreadPoolDir)\threadsafe_queue.h" />
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="$(ThreadPoolDir)\thread_pool.h" />
  </ItemGroup>
</Project>